#strings
import time
string = 'Hello There Bob'
print(len(string))
time.sleep(0.5)
print(string[0])
time.sleep(0.5)
print(string[4])
time.sleep(0.5)
print(string[len(string)-1])
time.sleep(1)
for ch in string:
 print(ch)
 time.sleep(0.25)
time.sleep(0.5)
for ch in range(0,len(string)):
 print(string[ch])
 time.sleep(0.25)
time.sleep(0.5)
for ch in range(0,len(string)):
 print(ch)
 time.sleep(0.25)
time.sleep(1)
print(string.upper())
time.sleep(0.5)
print(string.lower())
time.sleep(0.5)
print(string.count("e"))
time.sleep(0.5)
print(string.find("e"))
time.sleep(0.5)
print(string.replace("Bob","piss man"))
time.sleep(0.5)
print(string.islower())
time.sleep(0.5)
print(string.isupper())
time.sleep(0.5)
print(string.isalnum())
time.sleep(0.5)
print(string.isalpha())
time.sleep(0.5)
print(string.isdigit())
time.sleep(0.5)
print(string.index("There"))
time.sleep(0.5)
print(string.strip("Bob"))